AllCops:
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'multi_xml.gemspec'

# Avoid long parameter lists
ParameterLists:
  Max: 3
  CountKeywordArgs: true

ClassLength:
  Max: 85

LineLength:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 12

# Avoid more than `Max` levels of nesting.
BlockNesting:
  Max: 5

# Align with the style guide.
CollectionMethods:
  PreferredMethods:
    map:      'map'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

# Disable documentation checking until a class needs to be documented once
Documentation:
  Enabled: false

# No spaces inside hash literals
SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Allow dots at the end of lines
DotPosition:
  Enabled: false

# Don't require magic comment at the top of every file
Encoding:
  Enabled: false

# Align ends correctly
EndAlignment:
  AlignWith: variable

# Indentation of when/else
CaseIndentation:
  IndentWhenRelativeTo: end
  IndentOneStep: false
